### ISSUE TITLE
You are squatting on the package name.

### ISSUE THREAD

**Issue by paramaggarwal** [ambitioninc/react-native-ui#2]
There is no functionality here, you didn't have to publish this to npm if you did not intend to squat on this name.

https://docs.npmjs.com/misc/disputes

**Comment by jeffrifwald** [comment]
@paramaggarwal This repo has existed for less than 24 hours. I promise there will be functionality here shortly. If you have any ideas on what you'd like to see here, feel free to open other issues and/or pull requests. Thanks!

**Comment by paramaggarwal** [comment]
Problem is this repo is published to npm and shows up on http://react.parts without having any functionality at all, 20 days in.

**Comment by jeffrifwald** [comment]
If you point me to a further-along repo that wants to use this name in npm, I'll release it.
